# Generated by Django 4.1.5 on 2023-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('prenda_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('prenda_id', models.AutoField(primary_key=True, serialize=False)),
                ('prenda_category', models.CharField(max_length=50)),
                ('prenda_price', models.IntegerField()),
                ('prenda_color', models.CharField(max_length=50)),
                ('prenda_size', models.CharField(max_length=50)),
                ('prenda_description', models.CharField(max_length=50)),
            ],
        ),
    ]
