# Generated by Django 4.1.5 on 2023-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_prenda_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.avif', upload_to='products'),
        ),
    ]
