# Generated by Django 4.1.5 on 2023-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_clothes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default='/static/image/default.avif', upload_to='store/storage/images'),
        ),
    ]
